Unit11 course project
ChepaKN/JavaSIS-3.20 pull request #19
Opened 2020-04-24 04:27 UTC by ChepaKN

2020-04-29 05:24 UTC, Mrak2017 requested changes
В целом работа хорошая, посмотрите замечания.
---
Михаил Павлов

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/controller/SessionRestController.java
> +@RequestMapping("api")
можно было указать "api/session", тогда бы не пришлось писать session для каждого метода

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/controller/dto/SessionItemDTO.java
> +    public Date     insertDate;
лучше использовать LocalDate для даты или LocalDateTime если нужно ещё и время.

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/data/QuestionRepository.java
> +    List<Question> findRandQuestions();
Можно использовать такой подход (findTop10ByLastname) https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.limit-query-result

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/entity/SessionEvent.java
> +    private Date date;
аналогично, лучше использовать LocalDate или LocalDateTime

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/QuestionServiceImpl.java
> +                                //перемешаем ответы
Интересная задумка :)

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/QuestionServiceImpl.java
> +        //Скроем правильные ответы от хитрых пользователей
Отлично!

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +                        new RuntimeException(String.format("Не найдем вопрос с id%s",
"Не найдеМ" или "Не найдеН"?

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +        //Результат в диапазоне [0:1]
Комментарий не ясен. Раз он относится ко всему методу, надо было его разместить над методом

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +                            question.getId()));
Интересная проверка, но я бы сказал, что она должна происходить на этапе сохранения вопроса с ответами

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +                            question.getId()));
1) А в чем тут проблема? Возможно составитель вопроса хотел именно так?
2) Опять же, проверку надо делать не на проверке сессии, а на сохранении вопроса

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +        double w = 0;
Переменные лучше называть более говорящими именами, тогда и комментарии с описанием бы не понадобились

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +            //todo: как быть с невыбранными верными ответами?
В каком кейсе формула их не учтет?

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +            answers.addAll(q.answersList.stream()
Я бы результат обработки потока вынес в отдельную переменную, которую уже подавал в .addAll.
Для читабельности

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +            selectedAnswerRepository.save(new SelectedAnswer(a, sessionEvent));
почему бы сразу не сохранять внутри прошлого for? тогда не понадобится промежуточная переменная со списком ответов.

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> +        return String.format(Locale.US, "%.2f", result);
Можно было бы сделать replace внутри самой DTO ответа.

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/test/java/com/github/siberianintegrationsystems/restApp/RestAppApplicationTests.java
> +		//Проверим что все зависимости подтянулись
Были случаи когда не подтягивались? За это отвечает спринг, зачем его перепроверять?

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/test/java/com/github/siberianintegrationsystems/restApp/RestAppApplicationTests.java
> +		//Проверим что все зависимости подтянулись
Тем более в дальнейших тестах этой проверки уже нет. Следуя логике, зависимости могли не подтянуться и там.

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/test/java/com/github/siberianintegrationsystems/restApp/service/JournalServiceImplTest.java
> +    public void getJournal() {
лучше называть метод testGetJournal, иначе создается впечатление, что это вспомогательный метод, который должен вернуть журнал.

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/test/java/com/github/siberianintegrationsystems/restApp/service/QuestionServiceImplTest.java
> +        QuestionsItemDTO createdQuestion = questionService.createQuestion(questionsItemDTO);
разве в методе init не был создан точно такой же вопрос?

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/test/java/com/github/siberianintegrationsystems/restApp/service/QuestionServiceImplTest.java
> +        createdQuestion.answers.remove(0);
можно было бы ещё проверить, что не удастся сохранить вопрос, без ответов. Не критично

2020-04-29 05:24 UTC, Mrak2017 commented on unit-11/app-server/src/test/java/com/github/siberianintegrationsystems/restApp/service/QuestionServiceImplTest.java
> +        //все ответы к вопросу должны быть false;
я бы уточнил в комментарии, что ситуация штатная, т.к. мы заранее очищаем правильность ответов, перед отправкой на клиент. Иначе поведение, что нет ни одного правильного ответа по началу вводит в заблуждение

2020-04-29 05:50 UTC, ChepaKN commented
Здравствуйте, Михаил. Пробежался по замечаниям, практичен со всем
согласен..:) есть необходимость присылать исправления?

ср, 29 апр. 2020 г., 12:25 Mikhail <notifications@github.com>:

> *@Mrak2017* requested changes on this pull request.
> В целом работа хорошая, посмотрите замечания.
>
> Михаил Павлов
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/controller/SessionRestController.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417051725>:
>
> > @@ -0,0 +1,37 @@
> +package com.github.siberianintegrationsystems.restApp.controller;
> +
> +
> +import com.github.siberianintegrationsystems.restApp.controller.dto.QuestionsItemDTO;
> +import com.github.siberianintegrationsystems.restApp.controller.dto.session.SessionDTO;
> +import com.github.siberianintegrationsystems.restApp.service.QuestionService;
> +import com.github.siberianintegrationsystems.restApp.service.SessionService;
> +import org.springframework.web.bind.annotation.*;
> +import java.util.List;
> +
> +@RestController
> +@CrossOrigin(origins = "*")
> +@RequestMapping("api")
>
> можно было указать "api/session", тогда бы не пришлось писать session для
> каждого метода
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/controller/dto/SessionItemDTO.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417056908>:
>
> > @@ -0,0 +1,23 @@
> +package com.github.siberianintegrationsystems.restApp.controller.dto;
> +
> +import com.github.siberianintegrationsystems.restApp.controller.dto.journal.JournalItemDTO;
> +import com.github.siberianintegrationsystems.restApp.entity.SessionEvent;
> +import java.util.Date;
> +
> +public class SessionItemDTO extends JournalItemDTO {
> +
> +    public String   name;
> +    public Date     insertDate;
>
> лучше использовать LocalDate для даты или LocalDateTime если нужно ещё и
> время.
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/data/QuestionRepository.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417058321>:
>
> > @@ -9,4 +10,10 @@
>          extends CrudRepository<Question, Long> {
>
>      List<Question> findByNameContainingIgnoreCase(String search);
> +
> +    //todo: как бы вынести эту константу в настройки
> +    int questionsPerSession = 2;
> +    @Query(value = "SELECT * FROM QUESTION ORDER BY RAND() LIMIT " +
> +            questionsPerSession, nativeQuery = true)
> +    List<Question> findRandQuestions();
>
> Можно использовать такой подход (findTop10ByLastname)
> https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.limit-query-result
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/entity/SessionEvent.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417058540>:
>
> > @@ -0,0 +1,41 @@
> +package com.github.siberianintegrationsystems.restApp.entity;
> +
> +import javax.persistence.*;
> +import java.time.LocalDateTime;
> +import java.util.Date;
> +
> +@Entity
> +public class SessionEvent extends BaseEntity {
> +
> +
> +    @Column
> +    private Date date;
>
> аналогично, лучше использовать LocalDate или LocalDateTime
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/QuestionServiceImpl.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417061370>:
>
> >              answerRepository.save(answer);
>          }
>
>          return new QuestionsItemDTO(question,
>                  answerRepository.findByQuestion(question));
>      }
> +
> +    @Override
> +    public List<QuestionsItemDTO> getQuestionsForSession(){
> +
> +
> +        List<QuestionsItemDTO> questionsItemDTOList =
> +                questionRepository.findRandQuestions()
> +                    .stream()
> +                    .map(question -> {
> +                                //перемешаем ответы
>
> Интересная задумка :)
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/QuestionServiceImpl.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417061782>:
>
> > +
> +        List<QuestionsItemDTO> questionsItemDTOList =
> +                questionRepository.findRandQuestions()
> +                    .stream()
> +                    .map(question -> {
> +                                //перемешаем ответы
> +                                // todo: (как то не очень, переделать бы...)
> +                                List<Answer> answers = answerRepository.findByQuestion(question);
> +                                Collections.shuffle(answers);
> +                                return new QuestionsItemDTO(question,
> +                                        answers);
> +                            }
> +                    )
> +                    .collect(Collectors.toList());
> +
> +        //Скроем правильные ответы от хитрых пользователей
>
> Отлично!
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417062006>:
>
> > +                              AnswerRepository answerRepository,
> +                              SelectedAnswerRepository selectedAnswerRepository) {
> +        this.sessionEventRepository = sessionEventRepository;
> +        this.questionRepository = questionRepository;
> +        this.answerRepository = answerRepository;
> +        this.selectedAnswerRepository = selectedAnswerRepository;
> +    }
> +
> +
> +
> +    private double validateOneQuestion(QuestionSessionDTO questionSessionDTO){
> +        //Результат в диапазоне [0:1]
> +        Question question = questionRepository
> +                .findById(Long.parseLong(questionSessionDTO.id))
> +                .orElseThrow(() ->
> +                        new RuntimeException(String.format("Не найдем вопрос с id%s",
>
> "Не найдеМ" или "Не найдеН"?
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417062225>:
>
> > +
> +
> +    public SessionServiceImpl(SessionEventRepository sessionEventRepository,
> +                              QuestionRepository questionRepository,
> +                              AnswerRepository answerRepository,
> +                              SelectedAnswerRepository selectedAnswerRepository) {
> +        this.sessionEventRepository = sessionEventRepository;
> +        this.questionRepository = questionRepository;
> +        this.answerRepository = answerRepository;
> +        this.selectedAnswerRepository = selectedAnswerRepository;
> +    }
> +
> +
> +
> +    private double validateOneQuestion(QuestionSessionDTO questionSessionDTO){
> +        //Результат в диапазоне [0:1]
>
> Комментарий не ясен. Раз он относится ко всему методу, надо было его
> разместить над методом
> ------------------------------
>
> In
> unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/SessionServiceImpl.java
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#discussion_r417062513>:
>
> > +                .orElseThrow(() ->
> +                        new RuntimeException(String.format("Не найдем вопрос с id%s",
> +                                questionSessionDTO.id)));
> +
> +        //всего ответов
> +        double n = questionSessionDTO.answersList.size();
> +        //всего верных для этого вопроса
> +        double m = answerRepository.findByQuestion(question)
> +                .stream()
> +                .filter(Answer::getCorrect)
> +                .count();
> +
> +   [...]

2020-04-29 05:52 UTC, Mrak2017 commented
Да, желательно исправить, чтобы довести работу до логического завершения

2020-04-29 07:51 UTC, ChepaKN commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/data/QuestionRepository.java
> +    List<Question> findRandQuestions();
Здесь проблема скорее не в колличестве вопросов, а в случайном выборе их из базы. Про findTop я читал, но решил оставить так.

2020-04-30 04:29 UTC, ChepaKN commented
https://github.com/ChepaKN/JavaSIS-3.20/pull/20

Здравствуйте, высылаю исправления по замечаниям

ср, 29 апр. 2020 г., 12:52 Mikhail <notifications@github.com>:

> Да, желательно исправить, чтобы довести работу до логического завершения
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ChepaKN/JavaSIS-3.20/pull/19#issuecomment-621004544>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKWSJO423HCQ3EHZZTUA7PLRO66BXANCNFSM4MPYVXRQ>
> .
>

2020-04-30 07:51 UTC, merged